### ISSUE TITLE
Do not use Google news 

### ISSUE THREAD

**Issue by AshwinSankar17** [AshwinSankar17/NewsCluster#3]
Google news already provides clustered results.
The "NewsCluster" should cluster random news pulled from various sources( in future ).
Try doing it with other websites.

**Comment by AshwinSankar17** [comment]
Fixed with the latest commit

**Comment by AshwinSankar17** [comment]
Using cnn as the default website to be scraped.

**Comment by PandaWhoCodes** [comment]
Repopulate results with at least 200 news articles.
