### ISSUE TITLE
Check if url already exists in database 

### ISSUE THREAD

**Issue by PandaWhoCodes** [AshwinSankar17/NewsCluster#7]
Before you download and parse the article.

**Comment by AshwinSankar17** [comment]
Parsing possible only after download. News item is made primary key, so there's no duplicate.

**Comment by PandaWhoCodes** [comment]
I dont see a database schema anywhere.
Create a create_db.py file that contains the schema and running which will create the necessary tables for every new system.

**Comment by AshwinSankar17** [comment]
The tables are automatically created when running the to_db module.
